services:
  momentum-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momentum-ingestion-worker
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_KEY=${PREFECT_API_KEY}
    command: >
      bash -c "uv run prefect worker start --pool '${WORKER_POOL_NAME:-momentum-worker-pool}'"

networks:
  default:
    name: momentum-network
    external: false
